-- Script generated by Harry Lynas' basic C to Lua compiler.

print("test.c.lua was compiled on: Mar  6 2014 at 19:50:09 by Harry Lynas' basic C to Lua compiler.")

local function main()
local x = 
-- Automatically call main upon script being run
-- if there is a return print it
local isReturn = main()
if (isReturn) then
	print(tostring(isReturn))
end
